import type { Workshop, NewsArticle, Testimonial, Project, GalleryImage } from '@/types'

const img = (seed: string, w = 800, h = 500) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`

export const MOCK_WORKSHOPS: Workshop[] = [
  {
    id: '1',
    slug: 'fundamentals-of-acting',
    title: 'Fundamentals of Screen Acting',
    description: 'A deep dive into the craft of screen acting. Learn the Stanislavski method, emotional memory, and how to work in front of the camera with authenticity. Designed for beginners who want to make their mark in Bollywood.',
    shortDescription: 'Master the basics of screen acting with our signature method workshop.',
    image: img('acting1', 800, 500),
    date: '2026-07-15',
    endDate: '2026-07-17',
    location: 'Mumbai',
    duration: '3 Days',
    fees: '8,500',
    ageGroup: '18-35 years',
    time: '10:00 AM - 6:00 PM',
    venue: 'Acs Films Studio, Andheri West, Mumbai',
    tags: ['Acting', 'Beginner', 'Screen'],
    instructor: 'Mukesh Chhabra',
    instructorBio: 'Founder of Acs Films and one of India\'s foremost casting directors.',
    capacity: 20,
    enrolled: 14,
    isFeatured: true,
  },
  {
    id: '2',
    slug: 'advanced-character-work',
    title: 'Advanced Character Workshop',
    description: 'For trained actors who want to push their limits. Explore character transformation, dialect coaching, and intensive scene study with established filmmakers.',
    shortDescription: 'Push your boundaries with advanced character and scene study.',
    image: img('acting2', 800, 500),
    date: '2026-08-05',
    endDate: '2026-08-10',
    location: 'Delhi',
    duration: '6 Days',
    fees: '15,000',
    ageGroup: '21-45 years',
    time: '9:00 AM - 7:00 PM',
    venue: 'Delhi Arts Centre, Connaught Place',
    tags: ['Acting', 'Advanced', 'Character'],
    instructor: 'Anupama Chopra',
    capacity: 15,
    enrolled: 9,
    isFeatured: true,
  },
  {
    id: '3',
    slug: 'young-stars-workshop',
    title: "Young Stars: Children's Acting Program",
    description: 'A fun, nurturing environment where children between 8-16 learn the basics of performance, storytelling, and self-expression through games and guided exercises.',
    shortDescription: 'A nurturing program for young performers aged 8-16.',
    image: img('children1', 800, 500),
    date: '2026-07-20',
    location: 'Mumbai',
    duration: '2 Days',
    fees: '3,500',
    ageGroup: '8-16 years',
    time: '10:00 AM - 3:00 PM',
    venue: 'Acs Films Studio, Andheri West',
    tags: ['Children', 'Beginner', 'Fun'],
    instructor: 'Priya Sharma',
    capacity: 25,
    enrolled: 18,
    isFeatured: true,
  },
  {
    id: '4',
    slug: 'theatre-masterclass',
    title: 'Theatre Masterclass with NSD Alumni',
    description: 'An exclusive masterclass conducted by National School of Drama alumni. Explore classical and contemporary theatre techniques that inform exceptional screen acting.',
    shortDescription: 'Learn theatre craft from National School of Drama alumni.',
    image: img('theatre1', 800, 500),
    date: '2026-09-12',
    location: 'Bengaluru',
    duration: '1 Day',
    fees: '5,000',
    ageGroup: '20+ years',
    time: '11:00 AM - 5:00 PM',
    venue: 'Ranga Shankara, JP Nagar',
    tags: ['Theatre', 'Masterclass', 'Advanced'],
    instructor: 'NSD Alumni Guest',
    capacity: 50,
    enrolled: 37,
    isFeatured: false,
  },
  {
    id: '5',
    slug: 'audition-ready',
    title: 'Audition Ready Bootcamp',
    description: 'Get camera-ready for auditions. This intensive 2-day program covers self-tape techniques, cold reading, how to handle callbacks, and building a compelling showreel.',
    shortDescription: 'Master self-tape auditions and cold reading techniques.',
    image: img('audition1', 800, 500),
    date: '2026-07-28',
    location: 'Pune',
    duration: '2 Days',
    fees: '6,000',
    ageGroup: '18-40 years',
    time: '9:30 AM - 5:30 PM',
    venue: 'Film Institute, Pune',
    tags: ['Audition', 'Self-tape', 'Career'],
    instructor: 'Ritu Nanda',
    capacity: 30,
    enrolled: 22,
    isFeatured: true,
  },
  {
    id: '6',
    slug: 'voice-and-diction',
    title: 'Voice, Diction & Dialogue Workshop',
    description: 'Discover your voice. Work on resonance, clarity, accent neutralisation and expressive dialogue delivery for film and television.',
    shortDescription: 'Unlock your vocal potential for screen and stage.',
    image: img('voice1', 800, 500),
    date: '2026-08-22',
    location: 'Online',
    duration: '4 Days',
    fees: '4,200',
    ageGroup: '16+ years',
    time: '7:00 PM - 9:00 PM',
    venue: 'Online (Zoom)',
    tags: ['Voice', 'Diction', 'Online'],
    instructor: 'Kavita Menon',
    capacity: 40,
    enrolled: 29,
    isFeatured: false,
  },
]

export const MOCK_NEWS: NewsArticle[] = [
  {
    id: '1',
    slug: 'acs-announces-border-2-casting',
    title: 'Acs Films Completes Casting for Border 2 - A Landmark Ensemble',
    excerpt: 'Mukesh Chhabra Casting Company has finalised the massive ensemble cast for the much-anticipated sequel Border 2, slated for a 2026 release.',
    content: 'Full article content here...',
    image: img('news1', 800, 450),
    date: '2026-06-10',
    author: 'Acs Films Press',
    category: 'Announcements',
    tags: ['Casting', 'Bollywood', 'Border 2'],
  },
  {
    id: '2',
    slug: 'mukesh-chhabra-at-cannes',
    title: 'Mukesh Chhabra Represents Indian Casting at Cannes 2026',
    excerpt: 'Our founder represented India at the Cannes Film Festival, participating in a panel discussion on talent discovery in South Asian cinema.',
    content: 'Full article content here...',
    image: img('news2', 800, 450),
    date: '2026-05-22',
    author: 'Editorial Team',
    category: 'Events',
    tags: ['Cannes', 'International', 'Mukesh Chhabra'],
  },
  {
    id: '3',
    slug: 'summer-workshop-2026-open',
    title: 'Summer Workshop 2026 Registrations Now Open',
    excerpt: 'Applications for our flagship summer acting workshop are now live. Early bird pricing available till July 1st, 2026.',
    content: 'Full article content here...',
    image: img('news3', 800, 450),
    date: '2026-06-01',
    author: 'Workshop Team',
    category: 'Workshops',
    tags: ['Workshop', 'Summer', 'Registration'],
  },
  {
    id: '4',
    slug: 'pratik-gandhi-masterclass-recap',
    title: 'Inside the Pratik Gandhi Masterclass - An Afternoon of Craft',
    excerpt: 'Recap of our exclusive session with Pratik Gandhi, where he spoke candidly about his journey, audition failures, and the role Acs Films played in his breakout.',
    content: 'Full article content here...',
    image: img('news4', 800, 450),
    date: '2026-04-15',
    author: 'Content Team',
    category: 'Masterclass',
    tags: ['Masterclass', 'Pratik Gandhi', 'Bollywood'],
  },
  {
    id: '5',
    slug: 'acs-csa-member',
    title: 'Acs Films Becomes Member of Casting Society of America',
    excerpt: 'In a proud milestone, Acs Films has been inducted as a member of the Casting Society of America (CSA), joining an elite global casting community.',
    content: 'Full article content here...',
    image: img('news5', 800, 450),
    date: '2026-03-08',
    author: 'Acs Films Press',
    category: 'Awards',
    tags: ['CSA', 'International', 'Milestone'],
  },
  {
    id: '6',
    slug: 'new-acs-pune-studio',
    title: 'Acs Films Opens Doors to New Pune Studio',
    excerpt: 'We have expanded our footprint with a brand-new state-of-the-art studio in Pune, equipped for self-tape auditions, workshops, and casting sessions.',
    content: 'Full article content here...',
    image: img('news6', 800, 450),
    date: '2026-02-20',
    author: 'Editorial Team',
    category: 'Announcements',
    tags: ['Studio', 'Pune', 'Expansion'],
  },
]

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Aarav Mehta',
    role: 'Actor, Web Series',
    avatar: img('avatar1', 100, 100),
    quote: 'The Acs Films workshop was the turning point of my career. I walked in as an amateur and walked out with the confidence and tools to actually book roles. Within three months of attending, I had my first web series.',
    project: 'Panchayat Season 4',
    rating: 5,
  },
  {
    id: '2',
    name: 'Priya Kapoor',
    role: 'Actress & Theatre Artist',
    avatar: img('avatar2', 100, 100),
    quote: "Mukesh sir has an extraordinary eye for talent. His feedback during the audition workshop helped me understand what casting directors actually look for - practical, honest, and career-changing.",
    project: 'Mirzapur 3',
    rating: 5,
  },
  {
    id: '3',
    name: 'Rohan Das',
    role: 'Student, Mumbai',
    avatar: img('avatar3', 100, 100),
    quote: 'I came to Acs Films not knowing anything about the industry. The structured curriculum, the real audition simulations, and the mentorship made all the difference. Highly recommend to anyone serious about acting.',
    rating: 5,
  },
  {
    id: '4',
    name: 'Sneha Iyer',
    role: "Child Actor's Parent",
    avatar: img('avatar4', 100, 100),
    quote: "The children's program is exceptional. My daughter became so much more expressive and confident. The instructors were patient, professional, and truly passionate about nurturing young talent.",
    rating: 5,
  },
  {
    id: '5',
    name: 'Vikram Nair',
    role: 'Trained Actor',
    avatar: img('avatar5', 100, 100),
    quote: 'The Advanced Character Workshop stretched me beyond what I thought was possible. Working alongside 14 other committed actors and a brilliant facilitator was an unforgettable experience.',
    project: 'Sacred Games 3',
    rating: 5,
  },
  {
    id: '6',
    name: 'Ananya Bose',
    role: 'Model turned Actor',
    avatar: img('avatar6', 100, 100),
    quote: "Acs Films's Audition Ready bootcamp saved me months of confusion. I finally understood how to approach self-tapes and what production teams want. I booked my first TV commercial the same week.",
    rating: 4,
  },
]

export const MOCK_PROJECTS: Project[] = [
  { id: '1', slug: 'border-2', title: 'Border 2', image: img('movie1', 400, 560), type: 'movie', year: 2026, status: 'released' },
  { id: '2', slug: 'dhurandar', title: 'Dhurandar', image: img('movie2', 400, 560), type: 'movie', year: 2026, status: 'released' },
  { id: '3', slug: 'shaitaan', title: 'Shaitaan', image: img('movie3', 400, 560), type: 'movie', year: 2024, status: 'released' },
  { id: '4', slug: 'kabir-singh', title: 'Kabir Singh', image: img('movie4', 400, 560), type: 'movie', year: 2019, status: 'released' },
  { id: '5', slug: 'chandu-champion', title: 'Chandu Champion', image: img('movie5', 400, 560), type: 'movie', year: 2024, status: 'released' },
  { id: '6', slug: 'baby-john', title: 'Baby John', image: img('movie6', 400, 560), type: 'movie', year: 2024, status: 'released' },
  { id: '7', slug: 'panchayat-s4', title: 'Panchayat S4', image: img('series1', 400, 560), type: 'web-series', year: 2025, status: 'released' },
  { id: '8', slug: 'mirzapur-s3', title: 'Mirzapur S3', image: img('series2', 400, 560), type: 'web-series', year: 2024, status: 'released' },
  { id: '9', slug: 'scam-2003', title: 'Scam 2003', image: img('series3', 400, 560), type: 'web-series', year: 2023, status: 'released' },
  { id: '10', slug: 'upcoming-1', title: 'Project Untitled', image: img('movie7', 400, 560), type: 'movie', year: 2026, status: 'upcoming' },
  { id: '11', slug: 'upcoming-2', title: 'Code Red', image: img('series4', 400, 560), type: 'web-series', year: 2026, status: 'upcoming' },
  { id: '12', slug: 'upcoming-3', title: 'The Reckoning', image: img('movie8', 400, 560), type: 'movie', year: 2027, status: 'upcoming' },
]

export const MOCK_GALLERY: GalleryImage[] = Array.from({ length: 12 }, (_, i) => ({
  id: String(i + 1),
  src: img(`gallery${i + 1}`, 600, 400),
  alt: `Acs Films Behind the Scenes ${i + 1}`,
  category: ['Behind the Scenes', 'Workshops', 'Events', 'Casting Sessions'][i % 4],
}))
